name: "Test Report"

on:
  workflow_run:
    workflows: [".NET"]
    types:
      - completed

env:
  project: Starter.API

jobs:
  report:
    name: "publish report (project: ${{ env.project }}, os: ${{ matrix.os }})"
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
    runs-on: ubuntu-latest
    steps:
      - name: Get short commit hash
        id: vars
        run: echo "::set-output name=sha_short::$(echo '${{ github.event.workflow_run.head_sha }}' | cut -c1-7)"
      - uses: dorny/test-reporter@v1
        with:
          artifact: ${{ env.project }}.Tests-${{ matrix.os }}-${{ steps.vars.outputs.sha_short }}
          name: .NET Tests
          path: "*.trx"
          reporter: dotnet-trx
