name: "Test Report"

on:
  workflow_run:
    workflows: [".NET"]
    types:
      - completed

jobs:
  report:
    name: "publish report (os: ${{ matrix.os }})"
    env:
      PROJECT_NAME: Starter.API
    strategy:
      matrix:
        os: [ubuntu-latest]
    runs-on: ubuntu-latest
    steps:
      - name: Get short commit hash
        id: vars
        run: echo "::set-output name=sha_short::$(echo '${{ github.event.workflow_run.head_sha }}' | cut -c1-7)"
      - uses: dorny/test-reporter@v1
        with:
          artifact: ${{ env.PROJECT_NAME }}.Tests-${{ matrix.os }}-${{ steps.vars.outputs.sha_short }}
          name: 'test results (os: ${{ matrix.os }})'
          path: "*.trx"
          reporter: dotnet-trx
